### ISSUE TITLE
Getting ResourceNotFoundException

### ISSUE THREAD

**Issue by jalateras** [evansolomon/nodejs-kinesis-client-library#18]
I am just trying out the example consumer on a kinesis stream i set up under my account but i get the following error.

It looks like i'm not passing the access.secret keys correctly but i can't seem to track down the issue. Any clues?

```
[jima@ master xxxxx-data-backup]$AWS_ACCESS_KEY_ID="XXXXXXXX" AWS_SECRET_ACCESS_KEY="XXXXXXX" ./node_modules/.bin/launch-kinesis-cluster  --consumer test/tools/kinesis-consumer.js --aws.region ap-southeast-2 --stream xxxxx-stage-backup
{"name":"KinesisClusterLauncher","hostname":"jimb.local","pid":34885,"level":30,"msg":"Forking CLI","time":"2015-07-29T03:49:51.910Z","v":0}
{"name":"KinesisClusterCLI","hostname":"jimb.local","pid":34886,"level":30,"msg":"Consumer app path: /Users/jima/xxxxx/workspace/xxxxx-data-backup/test/tools/kinesis-consumer.js","time":"2015-07-29T03:49:52.302Z","v":0}
{"name":"KinesisClusterCLI","hostname":"jimb.local","pid":34886,"level":30,"options":{"streamName":"xxxxx-stage-backup","awsConfig":{"region":"ap-southeast-2"},"localDynamo":false,"localKinesis":false},"msg":"Cluster options","time":"2015-07-29T03:49:52.305Z","v":0}
{"name":"KinesisClusterCLI","hostname":"jimb.local","pid":34886,"level":30,"msg":"Launching cluster","time":"2015-07-29T03:49:52.308Z","v":0}
{"name":"KinesisClusterCLI","hostname":"jimb.local","pid":34886,"level":30,"msg":"Spawned cluster jimb.local@34886@1438141792308","time":"2015-07-29T03:49:52.364Z","v":0}
{"name":"KinesisCluster","hostname":"jimb.local","pid":34886,"level":30,"msg":"Starting report cluster loop","time":"2015-07-29T03:49:52.764Z","v":0}
{"name":"KinesisCluster","hostname":"jimb.local","pid":34886,"level":30,"msg":"Starting external network fetch loop","time":"2015-07-29T03:49:52.765Z","v":0}
{"name":"KinesisCluster","hostname":"jimb.local","pid":34886,"level":50,"msg":"Error fetching available shards","time":"2015-07-29T03:49:53.185Z","v":0}
{"name":"KinesisCluster","hostname":"jimb.local","pid":34886,"level":50,"err":{"message":"Requested resource not found","name":"ResourceNotFoundException","stack":"ResourceNotFoundException: Requested resource not found\n    at Request.extractError (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/protocol/json.js:43:27)\n    at Request.callListeners (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:595:14)\n    at Request.transition (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:21:10)\n    at AcceptorStateMachine.runTo (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:37:9)\n    at Request.<anonymous> (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:597:12)\n    at Request.callListeners (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/sequential_executor.js:115:18)","code":"ResourceNotFoundException"},"msg":"Requested resource not found","time":"2015-07-29T03:49:53.188Z","v":0}
{"name":"KinesisCluster","hostname":"jimb.local","pid":34886,"level":30,"msg":"Killing all consumers","time":"2015-07-29T03:49:53.188Z","v":0}
events.js:85
      throw er; // Unhandled 'error' event
            ^
ResourceNotFoundException: Requested resource not found
    at Request.extractError (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.callListeners (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:595:14)
    at Request.transition (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:21:10)
    at AcceptorStateMachine.runTo (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:37:9)
    at Request.<anonymous> (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/request.js:597:12)
    at Request.callListeners (/Users/jima/xxxxx/workspace/xxxxx-data-backup/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
{"name":"KinesisClusterLauncher","hostname":"jimb.local","pid":34885,"level":30,"exitCode":1,"msg":"CLI exited, restarting in 5 seconds","time":"2015-07-29T03:49:53.194Z","v":0}
```

**Comment by jalateras** [comment]
Okay, I found that specifying `--table` resolved my issue

**Comment by evansolomon** [comment]
Any remaining issue here or safe to close?
