### ISSUE TITLE
Shutdown Reliability 

### ISSUE THREAD

**Issue by basdag** [evansolomon/nodejs-kinesis-client-library#3]
Hi again @evansolomon, continuing playing with your library I found out that the method `shutdown` from `AbstractConsumer` is not being call in a reliable a constantly way (the majority of the time it does not call it at all) in errors occurred inside `ConsumerCluster`, like for example (connectivity issues): 

```
{"name":"KinesisClusterLauncher","hostname":"xxxx","pid":12343,"level":30,"msg":"Forking CLI","time":"2015-02-11T00:37:36.500Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12344,"level":30,"msg":"Consumer app path: xxxx.js","time":"2015-02-11T00:37:36.808Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12344,"level":30,"options":{"tableName":"xxxx","streamName":"xxxx","awsConfig":{"region":"us-east-1"},"localDynamo":false},"msg":"Cluster options","time":"2015-02-11T00:37:36.810Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12344,"level":30,"msg":"Launching cluster","time":"2015-02-11T00:37:36.812Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12344,"level":30,"msg":"Spawned cluster xxxx@12344@1423615056813","time":"2015-02-11T00:37:36.855Z","v":0}
{"name":"KinesisCluster","hostname":"xxxx","pid":12344,"level":30,"msg":"Starting report cluster loop","time":"2015-02-11T00:37:36.947Z","v":0}
{"name":"KinesisCluster","hostname":"xxxx","pid":12344,"level":30,"msg":"Starting external network fetch loop","time":"2015-02-11T00:37:36.948Z","v":0}
{"name":"KinesisCluster","hostname":"xxxx","pid":12344,"level":30,"shardId":"shardId-000000000000","leaseCounter":640,"msg":"Found available shard","time":"2015-02-11T00:37:37.232Z","v":0}
{"name":"KinesisCluster","hostname":"xxxx","pid":12344,"level":30,"shardId":"shardId-000000000000","leaseCounter":640,"msg":"Spawning consumer","time":"2015-02-11T00:37:37.233Z","v":0}
{"name":"KinesisConsumer","streamName":"xxxx","shardId":"shardId-000000000000","hostname":"xxxx","pid":12345,"level":30,"leaseCounter":640,"tableName":"xxxx","msg":"Setting up lease","time":"2015-02-11T00:37:37.664Z","v":0}
{"name":"KinesisConsumer","streamName":"xxxx","shardId":"shardId-000000000000","hostname":"xxxx","pid":12345,"level":30,"checkpoint":"49547041228974240276529212720544234861542422341484544002","msg":"Got starting checkpoint","time":"2015-02-11T00:37:37.854Z","v":0}
{"name":"KinesisConsumer","streamName":"xxxx","shardId":"shardId-000000000000","hostname":"xxxx","pid":12345,"level":30,"iteratorType":"AFTER_SEQUENCE_NUMBER","sequenceNumber":"49547041228974240276529212720544234861542422341484544002","msg":"Updating shard iterator","time":"2015-02-11T00:37:37.855Z","v":0}
{"name":"KinesisConsumer","streamName":"xxxx","shardId":"shardId-000000000000","hostname":"xxxx","pid":12345,"level":30,"ShardIterator":"AAAAAAAAAAEoGXBnZDtgkS24r3lshdjPXyniFA9p8c/BBxmLAOzZ7V1m7IRziLKcgJXhCd94vMgUgZG0QOyIh2yUhm4ix3UN2w7Yj/7w8Hl8ExKaoNQNpDnCTyR9+tk0mb9/ggKiLAf8h9mqLyC6OAVkOKFBchURkf5dKAE4JUnMQc5bL0njtDd28FvvGbMMnAmBwPUHSKE8KoM2dJOlB1Guc90llEAk","msg":"Updated shard iterator","time":"2015-02-11T00:37:38.054Z","v":0}
{"name":"KinesisConsumer","streamName":"xxxx","shardId":"shardId-000000000000","hostname":"xxxx","pid":12345,"level":30,"msg":"Starting getRecords loop","time":"2015-02-11T00:37:38.075Z","v":0}
{"name":"KinesisConsumer","streamName":"xxxx","shardId":"shardId-000000000000","hostname":"xxxx","pid":12345,"level":30,"msg":"Starting reserveLease loop","time":"2015-02-11T00:37:38.077Z","v":0}
{"name":"KinesisCluster","hostname":"xxxx","pid":12344,"level":50,"msg":"Error fetching external network data","time":"2015-02-11T00:37:42.046Z","v":0}
{"name":"KinesisCluster","hostname":"xxxx","pid":12344,"level":50,"err":{"message":"Inaccessible host: `dynamodb.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.","name":"UnknownEndpoint","stack":"UnknownEndpoint: Inaccessible host: `dynamodb.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.\n    at Request.ENOTFOUND_ERROR (/xxxx/node_modules/aws-sdk/lib/event_listeners.js:358:46)\n    at Request.callListeners (/xxxx/node_modules/aws-sdk/lib/sequential_executor.js:100:18)\n    at Request.emit (/xxxx/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/xxxx/node_modules/aws-sdk/lib/request.js:604:14)\n    at ClientRequest.error (/xxxx/node_modules/aws-sdk/lib/event_listeners.js:204:22)\n    at ClientRequest.<anonymous> (/xxxx/node_modules/aws-sdk/lib/http/node.js:62:19)\n    at ClientRequest.emit (events.js:117:20)\n    at CleartextStream.socketErrorListener (http.js:1551:9)\n    at CleartextStream.emit (events.js:95:17)\n    at Socket.onerror (tls.js:1455:17)","code":"UnknownEndpoint"},"msg":"Inaccessible host: `dynamodb.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.","time":"2015-02-11T00:37:42.047Z","v":0}

events.js:72
        throw er; // Unhandled 'error' event
              ^
UnknownEndpoint: Inaccessible host: `dynamodb.us-east-1.amazonaws.com'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/xxxx/node_modules/aws-sdk/lib/event_listeners.js:358:46)
    at Request.callListeners (/xxxx/node_modules/aws-sdk/lib/sequential_executor.js:100:18)
    at Request.emit (/xxxx/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/xxxx/node_modules/aws-sdk/lib/request.js:604:14)
    at ClientRequest.error (/xxxx/node_modules/aws-sdk/lib/event_listeners.js:204:22)
    at ClientRequest.<anonymous> (/xxxx/node_modules/aws-sdk/lib/http/node.js:62:19)
    at ClientRequest.emit (events.js:117:20)
    at CleartextStream.socketErrorListener (http.js:1551:9)
    at CleartextStream.emit (events.js:95:17)
    at Socket.onerror (tls.js:1455:17)
{"name":"KinesisClusterLauncher","hostname":"xxxx","pid":12343,"level":30,"exitCode":8,"msg":"CLI exited, restarting in 5 seconds","time":"2015-02-11T00:37:42.053Z","v":0}
{"name":"KinesisClusterLauncher","hostname":"xxxx","pid":12343,"level":30,"msg":"Forking CLI","time":"2015-02-11T00:37:47.060Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12348,"level":30,"msg":"Consumer app path: /xxxx/events/kinesis_reader.js","time":"2015-02-11T00:37:47.382Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12348,"level":30,"options":{"tableName":"xxxx","streamName":"xxxx","awsConfig":{"region":"us-east-1"},"localDynamo":false},"msg":"Cluster options","time":"2015-02-11T00:37:47.383Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12348,"level":30,"msg":"Launching cluster","time":"2015-02-11T00:37:47.384Z","v":0}
{"name":"KinesisClusterCLI","hostname":"xxxx","pid":12348,"level":30,"msg":"Spawned cluster xxxx@12348@1423615067385","time":"2015-02-11T00:37:47.428Z","v":0}
```

As it can be seen `CLI exited, restarting in 5 seconds` but without `Starting shutdown` the consumers, which is important in some cases, were you need to send a notice to other process to start wrapping up the data that has been retrieve from `processRecords`. 

Moreover, I notice that inside `ConsumerCluster` the prototype `logAndEmitError`, is working well since is capturing the errors. However when it emits the error `this.emit('error', err)` it seems that abruptly reinitialize the cluster, were sometimes it give time to shutdown the consumers but the majority of the time it don't. If this `this.emit('error', err)` is removed, then the consumer start shutting down, but it do not reinitialize the cluster.

Please let me know if you need any other information.

Thanks for your time and help.

**Comment by evansolomon** [comment]
Good find.  The problem here is that when the cluster manager (`ConsumerCluster`) encounters an error, it doesn't care about whether there are any consumers it should try to shut down.  Although you didn't mention it, I think the same problem occurs in other cases like when the cluster intentionally kills a consumer.

Just removing the error event in `ConsumerCluster#logAndEmitError` actually doesn't help that much because an error actually did occur and the process should exit (letting it continue to run would be unsafe because once the error happens it's in an undefined state).

The best solution would be to try to explicitly shut down consumers whenever the cluster itself is exiting.  I will try to take a look at doing that soon.  If you're up for it, feel free to send a PR in the meantime.

Thanks!

**Comment by evansolomon** [comment]
I haven't tested it at all yet, but just threw together a quick idea in 27bc2908e8fa61fddd3defec537cba2bab3fc52d

If you have a minute to try it out and let me know if it works that would be cool

**Comment by basdag** [comment]
Hi @evansolomon  thanks again for your super fast reply. Thanks for the info, I am already running some test I would let you know if it works during today. In case that it needs more tweaks I will send a PR.

Thanks again for your time and support, I really appreciated.

Have a good one!
